### ISSUE TITLE
'NoneType' object has no attribute 'peer_id'

### ISSUE THREAD

**Issue by vkdsk** [LencoDigitexer/RAPy#2]
После python adobe.py выходит ошибка. Версия змейки 3.7.8

C:\python\RAPy-master>python adobe.py
i am started!
Traceback (most recent call last):
  File "adobe.py", line 239, in <module>
    server1.start()
  File "adobe.py", line 79, in start
    for event in self.long_poll.listen():
  File "C:\python\lib\site-packages\vk_api\bot_longpoll.py", line 285, in listen
    for event in self.check():
  File "C:\python\lib\site-packages\vk_api\bot_longpoll.py", line 264, in check
    for raw_event in response['updates']
  File "C:\python\lib\site-packages\vk_api\bot_longpoll.py", line 264, in <listcomp>
    for raw_event in response['updates']
  File "C:\python\lib\site-packages\vk_api\bot_longpoll.py", line 225, in _parse_event
    return event_class(raw_event)
  File "C:\python\lib\site-packages\vk_api\bot_longpoll.py", line 169, in __init__
    peer_id = self.obj.peer_id or self.message.peer_id
AttributeError: 'NoneType' object has no attribute 'peer_id'

**Comment by LencoDigitexer** [comment]
Добавил в README требования к ключу токена
https://github.com/LencoDigitexer/RAPy/commit/6387106e75f0c16a850f10a763ef925643a65e39
